// Processes raw product images (name + price encoded in filename) into
// slugged public assets + a generated products.js data module.
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { execFileSync } from 'node:child_process'

// Optimize a source image into a web-ready JPEG (resize + compress) using macOS sips.
// execFileSync passes args directly (no shell) so filenames with $ / spaces are safe.
// Falls back to a plain copy if sips is unavailable or fails.
function optimizeToJpg(src, outPath) {
  try {
    execFileSync('sips', ['-s', 'format', 'jpeg', '-s', 'formatOptions', '82', '-Z', '1500', src, '--out', outPath], {
      stdio: 'ignore',
    })
    if (!fs.existsSync(outPath)) throw new Error('sips produced no output')
  } catch {
    fs.copyFileSync(src, outPath)
  }
}

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, '..')
const SRC = path.join(root, 'assets')
const OUT_DIR = path.join(root, 'public', 'assets', 'products')
const DATA_FILE = path.join(root, 'src', 'data', 'products.js')

fs.mkdirSync(OUT_DIR, { recursive: true })
fs.mkdirSync(path.dirname(DATA_FILE), { recursive: true })

const slugify = (s) =>
  s
    .toLowerCase()
    .replace(/[’'"]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')

// Category / gender inference from the product name
function classify(name) {
  const n = name.toLowerCase()
  const kidsHints = ['hipster', 'trouser with white top', 'pallazo', 'floral three piece', 'green blue', 'mustard white', 'fuschia white']
  const menHints = ['broken suit', 'double breast', 'pin stripped suit', 'blue stripped', 'chinese collar']
  let gender = 'Women'
  if (kidsHints.some((h) => n.includes(h))) gender = 'Kids'
  else if (menHints.some((h) => n.includes(h))) gender = 'Men'

  let category = 'Ready to Wear'
  if (n.includes('blazer')) category = 'Blazers'
  else if (n.includes('blouse') || n.includes('camisole') || n.includes('top') && !n.includes('trouser')) category = 'Tops & Blouses'
  else if (n.includes('dress')) category = 'Dresses'
  else if (n.includes('skirt')) category = 'Skirts & Sets'
  else if (n.includes('suit')) category = 'Suits'
  else if (n.includes('trouser') || n.includes('pallazo') || n.includes('snota') || n.includes('hipster')) category = 'Trousers & Sets'
  return { gender, category }
}

// Products to drop from the catalogue (by slug) — flagged as not linking up / poor images.
const EXCLUDE = new Set(['broken-suits', 'navy-blue-hipster-with-white-top'])

const files = fs
  .readdirSync(SRC)
  // real products are images with a $price in the name; skip logos & stray/generated files
  .filter((f) => /\.(jpe?g|png|webp)$/i.test(f) && !/logo|chatgpt/i.test(f) && /\$\s*\d/.test(f))

// Parse & group by normalized name (merge duplicate shots into one product gallery)
const groups = new Map()
for (const file of files) {
  const ext = path.extname(file)
  const base = path.basename(file, ext)
  // price: last $ number
  const priceMatch = base.match(/\$\s*([0-9]+(?:\.[0-9]{1,2})?)/)
  const price = priceMatch ? Math.round(parseFloat(priceMatch[1])) : 100
  // name: strip price and trailing (2) markers / dashes
  let name = base
    .replace(/\$\s*[0-9]+(?:\.[0-9]{1,2})?/g, '')
    .replace(/\(\d+\)/g, '')
    .replace(/[–-]\s*$/, '')
    .replace(/\s+/g, ' ')
    .trim()
  name = name.replace(/\s*[–-]\s*/g, ' – ')
  // Title case-ish (keep existing caps words)
  const key = slugify(name)
  if (!groups.has(key)) groups.set(key, { name, price, files: [] })
  const g = groups.get(key)
  g.files.push(file)
  g.price = Math.min(g.price, price) // lowest listed
}

const products = []
let idx = 0
for (const [key, g] of groups) {
  if (EXCLUDE.has(key)) continue
  const { gender, category } = classify(g.name)
  const images = g.files.map((file, i) => {
    // normalize every product image to an optimized .jpg
    const outName = `${key}${i ? '-' + (i + 1) : ''}.jpg`
    optimizeToJpg(path.join(SRC, file), path.join(OUT_DIR, outName))
    return `/assets/products/${outName}`
  })
  idx += 1
  products.push({
    id: key,
    name: g.name,
    price: g.price,
    gender,
    category,
    images,
    // rotate some flags for merchandising
    bestSeller: idx % 3 === 0,
    isNew: idx % 4 === 0,
  })
}

// Sort: by gender then category then name
products.sort((a, b) => a.name.localeCompare(b.name))

const banner = `// AUTO-GENERATED by scripts/process-assets.mjs — do not edit by hand.\n`
const body =
  banner +
  `export const products = ${JSON.stringify(products, null, 2)}\n\n` +
  `export const categories = [...new Set(products.map((p) => p.category))].sort()\n` +
  `export const genders = ['Women', 'Men', 'Kids']\n`

fs.writeFileSync(DATA_FILE, body)

console.log(`Processed ${files.length} files -> ${products.length} products`)
console.log('Categories:', [...new Set(products.map((p) => p.category))].join(', '))
console.log('By gender:', ['Women', 'Men', 'Kids'].map((g) => `${g}:${products.filter((p) => p.gender === g).length}`).join('  '))
